-- Create product_parcels table for multi-parcel support
CREATE TABLE IF NOT EXISTS public.product_parcels (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    master_product_id BIGINT REFERENCES public.master_products(id) ON DELETE CASCADE,
    width NUMERIC DEFAULT 0,
    height NUMERIC DEFAULT 0,
    depth NUMERIC DEFAULT 0,
    weight NUMERIC DEFAULT 0,
    desi NUMERIC GENERATED ALWAYS AS ((width * height * depth) / 3000) STORED,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Add index for faster joining
CREATE INDEX IF NOT EXISTS idx_product_parcels_master_id ON public.product_parcels(master_product_id);

-- Optional: Add total_desi column updates trigger if needed, 
-- but we might calculate it on read or via application logic to keep it simple.
