
-- Kargo Entegrasyon tablosunu eksiksiz oluşturma/güncelleme scripti
create table if not exists public.cargo_connections (
  id bigint generated by default as identity primary key,
  provider text not null, -- 'Surat', 'DHL', etc.
  is_active boolean default false,
  username text,          -- Sürat Kargo Kullanıcı Adı
  password text,          -- Sürat Kargo Şifre
  api_key text,           -- DHL/Diğer API Key
  secret_key text,        -- DHL/Diğer Secret Key
  account_number text,    -- DHL Account No
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RLS Politikaları (Erişim İzinleri)
alter table public.cargo_connections enable row level security;

-- Herkese (şimdilik) okuma/yazma izni ver (Geliştirme süreci için)
create policy "Enable all access for cargo_connections"
on public.cargo_connections
for all
using (true)
with check (true);

-- Eğer tablo zaten varsa ve kolonlar eksikse ekle
do $$
begin
  if not exists (select 1 from information_schema.columns where table_name = 'cargo_connections' and column_name = 'username') then
    alter table public.cargo_connections add column username text;
  end if;
  if not exists (select 1 from information_schema.columns where table_name = 'cargo_connections' and column_name = 'password') then
    alter table public.cargo_connections add column password text;
  end if;
  if not exists (select 1 from information_schema.columns where table_name = 'cargo_connections' and column_name = 'api_key') then
    alter table public.cargo_connections add column api_key text;
  end if;
  if not exists (select 1 from information_schema.columns where table_name = 'cargo_connections' and column_name = 'secret_key') then
    alter table public.cargo_connections add column secret_key text;
  end if;
  if not exists (select 1 from information_schema.columns where table_name = 'cargo_connections' and column_name = 'account_number') then
    alter table public.cargo_connections add column account_number text;
  end if;
end $$;
