CREATE TABLE public.spare_parts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id TEXT,
    customer_name TEXT,
    customer_phone TEXT,
    customer_city TEXT,
    customer_district TEXT,
    customer_address TEXT,
    product_name TEXT,
    product_code TEXT,
    part_name TEXT,
    quantity INTEGER DEFAULT 1,
    desi INTEGER DEFAULT 1,
    reason TEXT DEFAULT 'Kargo Hasarı',
    responsible_staff TEXT,
    detailed_description TEXT,
    status TEXT DEFAULT 'Yeni',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- RLS Policies (Opsiyonel ama önerilir: Herkes okuyup yazabilsin şimdilik)
ALTER TABLE public.spare_parts ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable read access for all users" ON public.spare_parts FOR SELECT USING (true);
CREATE POLICY "Enable insert access for all users" ON public.spare_parts FOR INSERT WITH CHECK (true);
CREATE POLICY "Enable update access for all users" ON public.spare_parts FOR UPDATE USING (true);
CREATE POLICY "Enable delete access for all users" ON public.spare_parts FOR DELETE USING (true);
