-- Add columns to product_marketplaces to track detailed status and pricing
ALTER TABLE product_marketplaces 
ADD COLUMN IF NOT EXISTS remote_product_id TEXT,       -- ID on the marketplace
ADD COLUMN IF NOT EXISTS barcode TEXT,                 -- Specific barcode for this marketplace
ADD COLUMN IF NOT EXISTS current_sale_price NUMERIC,   -- Last fetched price
ADD COLUMN IF NOT EXISTS discounted_price NUMERIC,     -- Discounted price if any
ADD COLUMN IF NOT EXISTS competitor_price NUMERIC,     -- Lowest competitor price
ADD COLUMN IF NOT EXISTS buybox_winner BOOLEAN DEFAULT false, -- Do we have the buybox?
ADD COLUMN IF NOT EXISTS commission_amount NUMERIC,    -- Calculated commission
ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'Passive', -- 'Active', 'Passive', 'Suspended'
ADD COLUMN IF NOT EXISTS last_sync_at TIMESTAMP WITH TIME ZONE,       -- Last successful sync
ADD COLUMN IF NOT EXISTS last_price_check_at TIMESTAMP WITH TIME ZONE, -- Last time we fetched prices
ADD COLUMN IF NOT EXISTS sync_status TEXT DEFAULT 'Pending';             -- 'Synced', 'Pending', 'Error'

-- Add Unique Constraint for UPSERT operations (Safe execution)
DO $$ 
BEGIN
    ALTER TABLE product_marketplaces 
    ADD CONSTRAINT product_marketplaces_product_id_marketplace_id_key 
    UNIQUE (product_id, marketplace_id);
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

-- Create table for price change logs
CREATE TABLE IF NOT EXISTS marketplace_price_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT REFERENCES master_products(id) ON DELETE CASCADE,
    marketplace_id BIGINT REFERENCES marketplace_accounts(id) ON DELETE CASCADE,
    old_price NUMERIC,
    new_price NUMERIC,
    change_source TEXT, -- 'Manual', 'Auto-Sync', 'Bulk-Update', 'Marketplace-Fetch'
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS for the new table
ALTER TABLE marketplace_price_logs ENABLE ROW LEVEL SECURITY;

-- Policies (Drop first to avoid 'already exists' error)
DROP POLICY IF EXISTS "Enable read access for all users" ON marketplace_price_logs;
CREATE POLICY "Enable read access for all users" ON marketplace_price_logs FOR SELECT USING (true);

DROP POLICY IF EXISTS "Enable insert access for all users" ON marketplace_price_logs;
CREATE POLICY "Enable insert access for all users" ON marketplace_price_logs FOR INSERT WITH CHECK (true);
