-- 1. FACTORY SETTINGS
CREATE TABLE IF NOT EXISTS public.factory_settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    overhead_percentage NUMERIC DEFAULT 15,
    profit_margin NUMERIC DEFAULT 30,
    created_at TIMESTAMPTZ DEFAULT now()
);

-- Ensure default settings exist
INSERT INTO public.factory_settings (overhead_percentage, profit_margin)
SELECT 15, 30
WHERE NOT EXISTS (SELECT 1 FROM public.factory_settings);

-- 2. MATERIALS
CREATE TABLE IF NOT EXISTS public.materials (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    category TEXT NOT NULL, 
    unit TEXT NOT NULL,
    unit_price NUMERIC DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT now()
);

-- Fix: Add missing columns if table already existed without them
ALTER TABLE public.materials ADD COLUMN IF NOT EXISTS waste_percentage NUMERIC DEFAULT 10;
ALTER TABLE public.materials ADD COLUMN IF NOT EXISTS sheet_width NUMERIC DEFAULT 3660;
ALTER TABLE public.materials ADD COLUMN IF NOT EXISTS sheet_height NUMERIC DEFAULT 1830;
ALTER TABLE public.materials ADD COLUMN IF NOT EXISTS stock_quantity NUMERIC DEFAULT 0;

-- Insert defaults if empty
INSERT INTO public.materials (name, category, unit, unit_price, waste_percentage, sheet_width, sheet_height)
SELECT '18mm MDF Lam - Beyaz', 'Levha', 'plaka', 1200, 10, 3660, 1830
WHERE NOT EXISTS (SELECT 1 FROM public.materials WHERE name = '18mm MDF Lam - Beyaz');

INSERT INTO public.materials (name, category, unit, unit_price, waste_percentage)
SELECT '0.80mm PVC Bant - Beyaz', 'Kenar Bandı', 'mt', 5, 5
WHERE NOT EXISTS (SELECT 1 FROM public.materials WHERE name = '0.80mm PVC Bant - Beyaz');

INSERT INTO public.materials (name, category, unit, unit_price)
SELECT 'Minifix Takım', 'Hırdavat', 'takım', 2.50
WHERE NOT EXISTS (SELECT 1 FROM public.materials WHERE name = 'Minifix Takım');

INSERT INTO public.materials (name, category, unit, unit_price)
SELECT 'Kavela', 'Hırdavat', 'adet', 0.25
WHERE NOT EXISTS (SELECT 1 FROM public.materials WHERE name = 'Kavela');

INSERT INTO public.materials (name, category, unit, unit_price)
SELECT 'Karton Koli', 'Ambalaj', 'adet', 15.00
WHERE NOT EXISTS (SELECT 1 FROM public.materials WHERE name = 'Karton Koli');

INSERT INTO public.materials (name, category, unit, unit_price)
SELECT 'Genel İşçilik', 'İşçilik', 'saat', 150.00
WHERE NOT EXISTS (SELECT 1 FROM public.materials WHERE name = 'Genel İşçilik');


-- 3. PRODUCT CUTS (Kesim Listesi)
CREATE TABLE IF NOT EXISTS public.product_cuts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    master_product_id BIGINT REFERENCES public.master_products(id) ON DELETE CASCADE,
    description TEXT,
    width NUMERIC,
    height NUMERIC,
    quantity INTEGER DEFAULT 1,
    material_id BIGINT REFERENCES public.materials(id),
    band_long INTEGER DEFAULT 0, -- 0, 1, 2
    band_short INTEGER DEFAULT 0, -- 0, 1, 2
    band_material_id BIGINT REFERENCES public.materials(id),
    created_at TIMESTAMPTZ DEFAULT now()
);

-- 4. PRODUCT COMPONENTS (Hırdavat, İşçilik vs.)
CREATE TABLE IF NOT EXISTS public.product_components (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    master_product_id BIGINT REFERENCES public.master_products(id) ON DELETE CASCADE,
    material_id BIGINT REFERENCES public.materials(id),
    quantity NUMERIC DEFAULT 1,
    created_at TIMESTAMPTZ DEFAULT now()
);

-- 5. PRODUCT PARCELS (Koli Bilgileri)
CREATE TABLE IF NOT EXISTS public.product_parcels (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    master_product_id BIGINT REFERENCES public.master_products(id) ON DELETE CASCADE,
    width NUMERIC,
    height NUMERIC,
    depth NUMERIC,
    weight NUMERIC,
    desi NUMERIC,
    created_at TIMESTAMPTZ DEFAULT now()
);
